// GENERATED by datafrosch/tools/events/publish.py from events/*.md — do not edit by hand.

var EVENTS = {
  upcoming: [
    {
      date: "2026-09-10",
      time: "14:30 CEST",
      title: "Data cleaning is glorious",
      desc: "Ada and Jonathan on the messes you'll meet in data and how to clean them up, with practical demos.",
      image: "img/events/data-cleaning-is-glorious.png",
      link: "https://discord.com/events/1406642598646513858/1545484398210715789",
      meet: "https://meet.google.com/hzm-ttjj-kxe"
    },
    {
      date: "2026-09-24",
      time: "14:00 CEST",
      title: "OpenRefine meets AI",
      desc: "Hervé Letoqueux shows how to supercharge OpenRefine with LLMs to turn messy data into investigation-ready datasets.",
      image: "img/events/openrefine-meets-ai.png",
      link: "https://discord.com/events/1406642598646513858/1545430508639490108",
      meet: "https://meet.google.com/krj-yuio-jzy"
    },
  ],

  past: [
    {
      date: "2026-06-24",
      title: "Pondcast #7: A deep dive into maps & QGIS intro (with Jonathan)",
      desc: "What makes a good map for your story — what works, what to watch for, and a hands-on intro to QGIS, the best free mapping tool.",
      youtube: "https://www.youtube.com/watch?v=NQoOe6xXN3E"
    },
    {
      date: "2026-06-16",
      title: "Pondcast #6: How to code anything (with Ada & Johan)",
      desc: "No coding knowledge needed — a simple, systematic approach to conversations, context and prompting so you can get an LLM to code anything.",
      youtube: "https://www.youtube.com/watch?v=BHD8Cv4PvrI"
    },
    {
      date: "2026-05-14",
      title: "Pondcast #5: Text embeddings and how to use them",
      desc: "What text embeddings are and how to put them to work in practice.",
      youtube: "https://www.youtube.com/watch?v=_teY3H-sK4I"
    },
    {
      date: "2026-04-17",
      title: "Pondcast #4: Finding Stories in health expenses data with Ada",
      desc: "Uncovering narratives and insights from healthcare expenditure data.",
      youtube: "https://www.youtube.com/watch?v=DWnYlMLeG-k"
    },
    {
      date: "2026-03-25",
      title: "Pondcast #3: Calculate CO2 emissions with Thomas Goorden",
      desc: "Discussing methods for measuring carbon dioxide emissions.",
      youtube: "https://www.youtube.com/watch?v=qE9GMVyRoEI"
    },
    {
      date: "2026-01-14",
      title: "Pondcast #2: Investigating kindergartens with Freja Wedenborg",
      desc: "What 350 evaluation reports reveal about inequality between Copenhagen neighbourhoods.",
      youtube: "https://www.youtube.com/watch?v=lvSleNCANkI"
    },
    {
      date: "2025-12-03",
      title: "Pondcast #1: Scraper blocking and how to get around it",
      desc: "Practical approaches when websites block your scraper.",
      youtube: "https://www.youtube.com/watch?v=1yCykgFrZz0"
    },
  ]
};
