// GENERATED by datafrosch/tools/events/publish.py from events/*.md — do not edit by hand.

var EVENTS = {
  upcoming: [
    {
      date: "2026-10-21",
      time: "14:00 CEST",
      title: "Digital sovereignty",
      desc: "What digital sovereignty actually means, why we want it, and what stands in the way, with Santi van den Toorn.",
      image: "img/pondcast-thumbnails-events/10-santi-event.jpg",
      link: "https://discord.com/events/1406642598646513858/1555218437440016465",
      luma: "https://luma.com/r4hus2wc",
      meet: "https://meet.google.com/ead-dnfi-tpj"
    },
    {
      date: "2026-10-27",
      time: "14:00 CET",
      title: "It's all a harness, baby",
      desc: "What an agent harness is, and how to build your own, with Johan Schuijt.",
      image: "img/frosches/walking-the-robots.jpg",
      link: "https://discord.com/events/1406642598646513858/1555218447325995069",
      luma: "https://luma.com/unpgrv6k",
      meet: "https://meet.google.com/bsw-oqds-ujm"
    },
    {
      date: "2026-11-18",
      time: "14:30 CET",
      title: "Mining analogue data",
      desc: "Constanze Bayer shows how old guide books and other analog materials became a data treasure trove in her story on the industrialization of ski resorts.",
      image: "img/frosches/mining-vintage-frog.jpg",
      link: "https://discord.com/events/1406642598646513858/1555218462748708985",
      luma: "https://luma.com/8unfuo0i",
      meet: "https://meet.google.com/fta-krxb-xxo"
    },
  ],

  past: [
    {
      date: "2026-09-24",
      title: "OpenRefine meets AI",
      desc: "Hervé Letoqueux shows how to supercharge OpenRefine with LLMs to turn messy data into investigation-ready datasets.",
      youtube: "https://youtu.be/4DMNxmHzCpU"
    },
    {
      date: "2026-09-10",
      title: "Data cleaning is glorious",
      desc: "Ada and Jonathan on the messes you'll meet in data and how to clean them up, with practical demos.",
      youtube: "https://youtu.be/kE-uP7o6SQI"
    },
    {
      date: "2026-06-24",
      title: "Pondcast #7: A deep dive into maps & QGIS intro (with Jonathan)",
      desc: "What makes a good map for your story — what works, what to watch for, and a hands-on intro to QGIS, the best free mapping tool.",
      youtube: "https://www.youtube.com/watch?v=NQoOe6xXN3E"
    },
    {
      date: "2026-06-16",
      title: "Pondcast #6: How to code anything (with Ada & Johan)",
      desc: "No coding knowledge needed — a simple, systematic approach to conversations, context and prompting so you can get an LLM to code anything.",
      youtube: "https://www.youtube.com/watch?v=BHD8Cv4PvrI"
    },
    {
      date: "2026-05-14",
      title: "Pondcast #5: Text embeddings and how to use them",
      desc: "What text embeddings are and how to put them to work in practice.",
      youtube: "https://www.youtube.com/watch?v=_teY3H-sK4I"
    },
    {
      date: "2026-04-17",
      title: "Pondcast #4: Finding Stories in health expenses data with Ada",
      desc: "Uncovering narratives and insights from healthcare expenditure data.",
      youtube: "https://www.youtube.com/watch?v=DWnYlMLeG-k"
    },
    {
      date: "2026-03-25",
      title: "Pondcast #3: Calculate CO2 emissions with Thomas Goorden",
      desc: "Discussing methods for measuring carbon dioxide emissions.",
      youtube: "https://www.youtube.com/watch?v=qE9GMVyRoEI"
    },
    {
      date: "2026-01-14",
      title: "Pondcast #2: Investigating kindergartens with Freja Wedenborg",
      desc: "What 350 evaluation reports reveal about inequality between Copenhagen neighbourhoods.",
      youtube: "https://www.youtube.com/watch?v=lvSleNCANkI"
    },
    {
      date: "2025-12-03",
      title: "Pondcast #1: Scraper blocking and how to get around it",
      desc: "Practical approaches when websites block your scraper.",
      youtube: "https://www.youtube.com/watch?v=1yCykgFrZz0"
    },
  ]
};
